[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["Anton Gerasimov <anton.gerasimov@openmailbox.org>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
ws = "0.7.3"
serde_json = "1.0.9"
serde_derive = "1.0.27"
serde = "1.0.27"
lazy_static = "1.0.0"
